name: Publish driver-did-iden3 to Privado AWS ECR
on:
  push:
    tags:
      - 'v*.*.*-dev'
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PRIVADO_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_PRIVADO_ID }}
  ECR_REPOSITORY: driver-did-iden3

jobs:
  build_driver:
    env:
      STATE_CONTRACT_ADDRESS_POLYGON_MAIN: "0x624ce98D2d27b20b8f8d521723Df8fC4db71D79D"
      STATE_CONTRACT_ADDRESS_POLYGON_AMOY: "0x1a4cC30f2aA0377b0c3bc9848766D90cb4404124"
      STATE_CONTRACT_ADDRESS_PRIVADO_MAIN: "0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896"
      STATE_CONTRACT_ADDRESS_PRIVADO_TEST: "0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: driver-did-iden3

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/PolygonIDActionsRole
          role-session-name: GitHubActionsSession

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build file with supported networks
        run: |
          cd driver-did-iden3
          echo -e "polygon:" > resolvers.settings.yaml
          echo -e "  amoy:" >> resolvers.settings.yaml
          echo -e "    contractAddress: ${{ env.STATE_CONTRACT_ADDRESS_POLYGON_AMOY }}" >> resolvers.settings.yaml
          echo -e "    networkURL: ${{ secrets.POLYGON_AMOY_NODE_URL }}" >> resolvers.settings.yaml
          echo -e "    walletKey: ${{ secrets.SIGNER_PRIVATE_KEY }}" >> resolvers.settings.yaml
          echo -e "  main:" >> resolvers.settings.yaml
          echo -e "    contractAddress: ${{ env.STATE_CONTRACT_ADDRESS_POLYGON_MAIN }}" >> resolvers.settings.yaml
          echo -e "    networkURL: ${{ secrets.POLYGON_MAIN_NODE_URL }}" >> resolvers.settings.yaml
          echo -e "    walletKey: ${{ secrets.SIGNER_PRIVATE_KEY }}" >> resolvers.settings.yaml
          echo -e "privado:" >> resolvers.settings.yaml
          echo -e "  main:" >> resolvers.settings.yaml
          echo -e "    contractAddress: ${{ env.STATE_CONTRACT_ADDRESS_PRIVADO_MAIN }}" >> resolvers.settings.yaml
          echo -e "    networkURL: ${{ secrets.PRIVADO_MAIN_NODE_URL }}" >> resolvers.settings.yaml
          echo -e "    walletKey: ${{ secrets.SIGNER_PRIVATE_KEY }}" >> resolvers.settings.yaml
          echo -e "  test:" >> resolvers.settings.yaml
          echo -e "    contractAddress: ${{ env.STATE_CONTRACT_ADDRESS_PRIVADO_TEST }}" >> resolvers.settings.yaml
          echo -e "    networkURL: ${{ secrets.PRIVADO_TEST_NODE_URL }}" >> resolvers.settings.yaml
          echo -e "    walletKey: ${{ secrets.SIGNER_PRIVATE_KEY }}" >> resolvers.settings.yaml

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build and deploy to DockerHub
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          cd driver-did-iden3 && \
          docker buildx build --push \
           --platform linux/amd64,linux/arm64 \
           -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }} .
